name = input("Yo wsg, whats yo name cuh")
input("")
print(f"Nice to meet you {name}")
input("")
food = input(f"Yo {name} whats yo fav food??")
input("")
food = input(f"nah {food} are not it, french fries are the best")
input("")
print("guess what")
input("")
print("chicken butt")
input("")
print("i dont know what to type so im just doing this to meet the standards")
input("")
print("i actually have no clue what to type, 10 is way to many")
input("")
print("in know hwo to type print 10 is way to many")
input("")
print("why 10????????????????????????????????????????????????????????????")
input("")
print("10 is way to many")
input("")
print("guess what, 10 is way to many")
input("")
print("OMG THIS IS THE 10TH ONE")
name = input("bye {name}")